@hostname = localhost
@port = 9925
@host = {{hostname}}:{{port}}
@contentType = application/json

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "registration_info"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "get_fingerprint"
}